# dcgm-exporter
addons:
  dcgmExporter:
    enabled: true
    port: 9400
    image:
      repository: nvcr.io/nvidia/k8s/dcgm-exporter
      tag: 3.3.5-3.4.0-ubuntu22.04


# NVIDIA Device Plugin
  nvidiaDevicePlugin:
    enabled: true
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.16.2
    failOnInitError: "false"

# Prometheus Adapter
  prometheusAdapter:
    enabled: true
    service:
      port: 443
      targetPort: 6443
    image:
      repository: registry.k8s.io/prometheus-adapter/prometheus-adapter
      tag: v0.10.0
    prometheusUrl: "http://prometheus.monitoring.svc.cluster.local:9090"
    metricsRelistInterval: "30s"
    logVerbosity: 4
    rules:
      - seriesQuery: 'llm_request_queue_length{job="vllm"}'
        resources:
          overrides:
            pod: pod
            namespace: namespace
        name:
          matches: "llm_request_queue_length"
          as: "llm_request_queue_length"
        metricsQuery: 'avg(llm_request_queue_length{job="vllm"}) by (namespace, pod)'


# ServiceMonitor for LLM metrics
  serviceMonitor:
    enabled: true
    name: llm-metrics
    releaseLabel: prometheus
    namespaceSelector:
      - llm
    selector:
      app: llm
    endpoint:
      port: metrics
      interval: 15s
      path: /metrics
      scheme: http
