{{- if .Values.addons.prometheusAdapter.enabled }}

# ============================================================
# CONFIGMAP
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    rules:
{{- range .Values.addons.prometheusAdapter.rules }}
      - seriesQuery: {{ .seriesQuery | quote }}
        resources:
          overrides:
{{- range $key, $value := .resources.overrides }}
            {{ $key }}:
              resource: {{ $value }}
{{- end }}
        name:
          matches: {{ .name.matches | quote }}
          as: {{ .name.as | quote }}
        metricsQuery: {{ .metricsQuery | quote }}
{{- end }}

---
# ============================================================
# DEPLOYMENT
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      serviceAccountName: prometheus-adapter
      containers:
        - name: prometheus-adapter
          image: "{{ .Values.addons.prometheusAdapter.image.repository }}:{{ .Values.addons.prometheusAdapter.image.tag }}"
          args:
            - "--prometheus-url={{ .Values.addons.prometheusAdapter.prometheusUrl }}"
            - "--metrics-relist-interval={{ .Values.addons.prometheusAdapter.metricsRelistInterval }}"
            - "--v={{ .Values.addons.prometheusAdapter.logVerbosity }}"
            - "--config=/etc/adapter/config.yaml"
            - "--secure-port={{ .Values.addons.prometheusAdapter.service.targetPort }}"
          volumeMounts:
            - name: config
              mountPath: /etc/adapter
              readOnly: true
            - name: local-config
              mountPath: /apiserver.local.config
            - name: tmp-dir
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: adapter-config
        - name: local-config
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}

{{- end }}
